projects:
  app:
    schemaPath: src/graphql/schema.graphql
    extensions:
      endpoints: https://checklyst-server.herokuapp.com/CheckLyst-Server/dev
      default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: src/prisma/prisma.yml
